services:
  # Service for your Flask application (backend)
  app:
    build: . # Build the image from the Dockerfile in the current directory (ai-service folder)
    ports:
      - "5002:5002" # Map host port 5002 to container port 5002
    environment:
      # This environment variable will be available inside the 'app' container.
      # It points directly to your MongoDB Atlas cluster.
      MONGO_URI: mongodb+srv://shuvokumerraycse10:ZHQCNdl28SLEzjqe@cluster0.0doar1z.mongodb.net/digi-thesis_DB?retryWrites=true&w=majority&appName=Cluster0
      DB_NAME: digi-thesis_DB # Your database name
      COLLECTION_NAME: theses # Your collection name
